### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [mcat56/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [ ] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [x] Technical Ready
- [ ] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
Hey Mary,

Overall, great work on this. The actual content of your work looks really solid. I think both of your classes/examples look great and your top down design looks solid as well.

The main issue, which you already identified, is that you had multiple "Initial commit" messages which you mostly remedied by adding your additional commit messages. In the future, make sure that your commit message is reflective of the work that has been done in the commit. I have faith that you won't make this same mistake again 😄 

Also, since you put your top down design implementation in a text file instead of the markdown file, I would have made another commit to delete the empty markdown file.

**Comment by mcat56** [comment]
Thank you, that deletion is actually still sitting in git diff, and I thought with the file deleted that the change would actually not show since the file is gone, but it makes sense now that it's still a change to the repo and would be committed. I think I tried just removing the file from staging area with git reset file but then obviously I would get the error message the file was deleted, makes sense now! Thank you!
